# Generated by Django 2.2.5 on 2020-02-19 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worksite',
            old_name='Supervisor',
            new_name='supervisor',
        ),
    ]
